let content = {
    type: 'article',
    title: 'Boots Riley’s Career Is The Blueprint For Artivism',
    qoute: null,
    img: {
        a: '/resources/img/words/bother you/one.jpg',
        b: '/resources/img/words/bother you/two.jpg',
        c: '/resources/img/words/bother you/three.jpg'
    },
    short_des: "Riley’s work has always managed to fuse activism with art, and he’s participated in several community projects, cop-watch services and movements against FBI involvement in marijuana-related crime. He has even used the popularity of The Coup to round up audience members from their concerts to takeover closed meetings, thereby making them public. Riley was also an active supporter of the Occupy movement to the extent of which Rolling Stone deemed him the ‘most dynamic’ spokesperson of the Oakland occupation. When referred to as a communist, Riley’s response was sharp – stating, ‘I don’t care what you call it, as long as people have democratic control over the wealth they create.’",
    para: {
        a: "Boots Riley is never afraid to speak his mind. Having struck a discord with world renowned director, Spike Lee, on his latest blockbuster, Blackkklansman, Boots Riley took to Twitter to call him out in mid-August. Riley’s qualms stem from Blackkklansman’s false depiction of Ron Stallworth’s 2014 memoirs. In Riley’s own words, ‘without the made-up stuff, and with what we know of the actual history of police infiltration into radical groups, and how they infiltrated and directed white supremacist organisations to attack those groups, Ron Stallworth is the villain.’",
        b: 'Riley has never been shy to voice his opinion in the name of truth, which should come as no surprise considering he was born into a family of social justice organisers. It is this tenacity of character throughout his career that resonates with me most. His career started with a lead-rapper role in the political hip-hop group, The Coup, whose sound has been defined as ‘driven by assertive and danceable bass-driven backbeats overlaid by critical, hopeful, and witty lyrics.’  A masterpiece of theirs is the song Fat Cats and Bigga Fish which tells the story of a con-artist moving efficiently through life, told with charismatic and pronounced flow over a smooth and funky melody.',
        c: "Riley’s work has always managed to fuse activism with art, and he’s participated in several community projects, cop-watch services and movements against FBI involvement in marijuana-related crime. He has even used the popularity of The Coup to round up audience members from their concerts to takeover closed meetings, thereby making them public. Riley was also an active supporter of the Occupy movement to the extent of which Rolling Stone deemed him the ‘most dynamic’ spokesperson of the Oakland occupation. When referred to as a communist, Riley’s response was sharp – stating, ‘I don’t care what you call it, as long as people have democratic control over the wealth they create.’",
        d: 'Last year, we were treated to Riley’s debut movie, Sorry to Bother You; a film equated in significance to Jordan Peele’s Get Out (2017). What’s interesting about Riley’s directorial debut is that it was actually written in 2012. For an interview in GQ Magazine, Riley commented, ‘unfortunately the world hasn’t changed enough to make the movie irrelevant.’ To me, the film is cynical and quirky in its focus on the wildly-tedious world of telemarketing. While watching, I was constantly drawing parallels with Austin Powers – the vivid lighting, the sharp whip-pans accompanied by fairy dust sound effects, and the seemingly random addition of charming features such as Tessa Thompson’s earrings, akin to the out-of-place nature of Mike Myers’ elaborately hairy chest. At some points, I think the film goes slightly too far in its slam of capitalism. That being said, Riley manages to reel it back with fantastical shots, a funky soundtrack and a magical storyline. In effect, the audience is reminded that Sorry to Bother You is set in a dream world, but in leaving, you are gifted with a lens that opens your mind up to more critical thinking. For that lens, I applaud Riley.',
        e: 'With so much creativity in the film and so much thought in whatever he does, Boots Riley is not one to be forgotten or overlooked. I look forward to engaging in whatever magic he might produce in the future.'
    }
}

export default content