let content = {
    type: 'article',
    title:`Brilliant Storytelling and Racial Nuance Earned ‘Green Book’ The Oscar`,
    qoute: {
        a: 'we are reminded about Don Shirley’s ability to mute his Blackness',
        b: 'Don Shirley functions as a living contradiction'
    },
    img: {
        a: '../resources/img/words/green book/one.jpg',
        b: '../resources/img/words/green book/two.jpg'
    },
    short_des:`Having won Best Picture, Best Original Screenplay and Best Supporting Actor (for Mahershala Ali’s stunning performance), it is safe to say that despite Spike Lee’s petty remarks, Green Book stole the show at the 2019 Oscars. I have watched both Lee’s Blackkklansman and Green Book and I stand by the results.`,
    para: {
        a:    `Last night, a heart-warming story received the accolades it deserved. Having won Best Picture, Best Original Screenplay and Best Supporting Actor (for Mahershala Ali’s stunning performance), it is safe to say that despite Spike Lee’s petty remarks, Green Book stole the show at the 2019 Oscars. I have watched both Lee’s Blackkklansman and Green Book and I stand by the results. Though Blackkklansman was more visually stunning, its divergence from the real story for dramatic effect fails to hold weight when compared to the beautiful yet saddening story of Green Book. It stars Mahershala Ali as Don Shirley and polymath Viggo Mortensen as Tony ‘Lip’ Vallelonga. It is with the help of this skilful duo that we are guided through the world of Don Shirley in Green Book.
                The plot is simple: an African-American classical and jazz pianist, Don Shirley, needs a driver/bodyguard to safely escort him around the deep-south states of America during the ’60s. The deep-south was the sub-region in southern USA most dependent on plantations and slave societies, including places such as Georgia, Alabama, South Carolina, Mississippi, and Louisiana. Tony ‘Lip’ Vallelonga is chosen to escort the black Shirley through the most racist parts of the country.`,
        b:    `The film highlights two main tensions; the first stemming from the clash of the two main characters. Tony is a working class, vulgar bullshitter who dabbles in theft. In other words, he knows how to get things done and can handle himself if need be. What is also clear is that Tony is a racist who sees all Negroes as loving fried chicken or listening to Aretha Franklin. Don Shirley, on the other hand, does not fit this black identity – he has never tried fried chicken and eventually concludes it to be ‘unsanitary’. Instead, Don Shirley is a classy man who epitomises aristocracy. For instance, upon their first meeting, Don Shirley is planted firmly on a throne wearing white robes with golden seams and a golden chain adorned on his chest. Thus, the tension is that of Tony’s notion of black identity juxtaposed to the tangible black identity of Don Shirley. This tension is no more evident than when Tony yells “I’m blacker than you” in an argument with Shirley after Tony loses his cool with a cop. In this instance, we are reminded about Don Shirley’s ability to mute his blackness. He is angry at how easy Tony loses his cool, reminding him that “You never win with violence; you only win when you maintain your dignity. Dignity always prevails.”
                The second tension is Don Shirley’s black identity juxtaposed to black identity in the deep-south states. As the audience, we are constantly reminded that despite Don Shirley’s musical success, he remains restricted like any other black person. After all, that is why he hired Tony, and must navigate through the southern states with him according to the ‘Green Book’ – a guide to those ‘travelling when black’. Shirley is often denied entrance into shops, access to certain toilets, and when rewarded after his show, he is offered fried chicken. When in the black neighbourhood in Louisville, Kentucky, he is perceived as a butler because of his classy attire. In short, Shirley is always out of place and never at ease. A good scene to highlight this is when Shirley’s car breaks down near a farm filled with black workers. Shirley waits outside while Tony fixes the car, but in the near distance he is spotted by the blacks on the field. In this eerie scene, the farmers stop work to gawk at an upper echelon black man.`,
        c: `From both tensions, what is clear is that Don Shirley has always struggled with his identity. He does not fit into the black community because he is too upper class, and he does not fit into the white community because his skin is black. To me, Don Shirley functions as a living contradiction. He aims to transcend blackness because of the stigma that comes with being black. In so doing, Shirley dresses a certain way, talks a certain way, and performs in a certain way. Yet, he will always be black, and he is aware of this. This explains why he takes so many precautions. He hires Tony to drive him round, stays in ‘Green Book’ advised accommodation and has essentially become skilled at navigating through the white world, while failing to navigate through the black one. Here, his own words sum up my thoughts about Shirley’s character, “If I’m not black enough, if I’m not white enough, and if I’m not man enough, then tell me…what am I?”
                This film resists the over-saturation of visual techniques and instead, recognises the importance of telling the story correctly. Because of this, the director, Peter Farrelly, lets the story do the talking by using shots to solely set the stage while the story of Don Shirley does the rest of the work. This film deserved to win Best Picture because it tackles a highly nuanced racial phenomenon in a sensitive and reflective way. While not many African-Americans endured this lack of belonging brought about by wealth accumulation in the past, it is likely a more frequent catch-22 today – that is, of being trapped in the void of identity: neither identifying with blackness or whiteness.`
    }
}

export default content