let content = {
    type:'article',
    title: 'Why Should We Care About Islamic Banking?',
    qoute: {
        a: 'all interest is seen to be unreasonably high',
        b: 'no monolithic authority governs the industry',
        c: 'a failure to plan is a plan to fail'
    },
    img: {
        a: '/resources/img/words/islamic banking/one.jpg',
        b: '/resources/img/words/islamic banking/two.jpg',
        c: '/resources/img/words/islamic banking/three.jpg'
    },
    short_des: 'Historically, human societies have often had a demand for a medium of exchange. This demand was originally facilitated by metallic money, then paper currency, later cheque deposits and finally modern digitalised currency. In this way, banking systems have provided convenient solutions to the problem of high demand for money supply. For one, they help the formation of national capital and production in the form of large loans made by nations. On top of this, they facilitate exchange, keep demand deposits, and provide safe custody of valuables in the form of safety deposit boxes. Equally, when concerned with payments made by individuals, they facilitate immediate monetary transfers to overseas and local recipients. In short, banking systems are useful, functional and they serve a purpose.',
    para: {
        a: 'In this piece, I will evaluate the pros and cons of Islamic banking to figure out whether it is truly worth our time. Financial transactions in the Islamic world have existed since the 7th Century in regions of the Middle East, and the 10th century in North Africa, however no institutions were exclusively devoted to a particular method of banking. In recent times, the global proliferation of Islamic banking has expanded across areas of Kenya, Iran, the Philippines, Malaysia, the UK, Germany, France, Egypt, Iran and many more.',
        b: 'Historically, human societies have often had a demand for a medium of exchange. This demand was originally facilitated by metallic money, then paper currency, later cheque deposits and finally modern digitalised currency. In this way, banking systems have provided convenient solutions to the problem of high demand for money supply. For one, they help the formation of national capital and production in the form of large loans made by nations. On top of this, they facilitate exchange, keep demand deposits, and provide safe custody of valuables in the form of safety deposit boxes. Equally, when concerned with payments made by individuals, they facilitate immediate monetary transfers to overseas and local recipients. In short, banking systems are useful, functional and they serve a purpose.',
        c: 'History aside, the object of this article is to give a reasonable account of a different banking system, namely, Islamic banking (IB). The topic itself is quite convoluted so to simplify matters I have attempted to focus on 7 key points that I think are most important.',
        d: '1. IB is a non-interest based banking system whereas conventional banking (CB) systems are jam-packed with interest. In short, IB is finance compliant with Sharia law – a compliance which prohibits interest (riba) on the grounds that it constitutes unfair trade. The argument for this prohibition stems from the idea that increased increments in repayment fees are unjustified. Under this account, the repayment fee which makes the overall fee above the amount loaned is an imposition by the lender. By this philosophy, all interest is seen to be unreasonably high since there should be no repayment fee when helping a person in need.',
        e: '2. IB is compliant with Sharia law. Because of IB’s Sharia compliance, its products do not support any haraam (forbidden) goods/services nor do they lend to companies that sell haraam products – i.e. pork, alcohol.',
        f: '3. Islamic scholars and economists promote IB as a sufficient replacement for CB systems. For instance, Mohammad Najatuallah Siddiqui states that interest-based banking systems result in various negative effects such as inequities in the distribution of income and wealth – i.e. outcomes such as the 99% versus the 1%. Arguably it also furthers the concentration of economic power which leads to a tendency towards inflation and fast accumulation of debt in various economic sectors, resulting in serious political, economic, and social consequences. We need only attend to the current situation in Venezuela to recognise the social impacts a failed conventional banking system has on surrounding sectors.',
        g: '4. IB encourages entrepreneurial enterprises while CB deters them. Under the latter system, entrepreneurs are encouraged to drop any foreseeably unsuccessful or highly risky endeavours due to the accumulative debt owed to banks. In this sense, interest rates for borrowing money from banks are treated as the price of money due to its relation to supply-demand, which subsequently affect cost curves and influence policies made by firms regarding pricing products. The idea is that as interest rates increase for the entrepreneur, this will affect how the entrepreneur determines their rate and cost of supply by influencing cost curves or pricing made by firms.',
        h: 'In addition to this, society is affected on multiple levels. For instance, public debt is exacerbated by the fixed price of loans in the investment market. Because of this, customers in need are opened up to the possibility of being exploited by interest-bearing loans whereby their situation is worsened by debt repayment, while other customers that take out interest-based loans are subject to any uncertainty characterised by their situation which varies depending on the result of inflation, income-earning, and other factors out of their control.',
        i: 'Moreover, when considering the international stage, it can be observed that poor countries are guided into debt as they aim to meet the standards of globalisation. For instance, an article in the Guardian describes how several sub-Saharan African countries “had been forced to seek help from the International Monetary Fund and the World Bank, adding that the international community needed to be better prepared to manage a new crisis.”',
        j: '5. IB also suffers the problem of weak financing. The inconsistencies in the bank lending practices can create impossible situations for the banks in which they lose money from the product. For Khemaies Bougatef, this is due to the fact that a) they provide interest-free loans; and b) offer credit sale products that, as stated by Professor Saiful Azhar Rosly, fail to recover the above receivables due to the bank’s own deficiency for not being prudent in credit valuation and debt collection.',
        k: 'For instance, take an asset which constitutes the profit produced from a building in the process of being constructed where fixed payments for the financial product are deferred to a later date. The financial output of this construction is uncertain since the precise accounting of requisite material may vary or the predicted profit may be inaccurate. Due to the fixed nature of the agreement, the bank suffers a necessary loss. If profit is over-predicted, the bank accommodates for the loss of the business in order to comply with Muslim tradition but if profit is under-predicted, the bank fails to receive a just portion.',
        l: 'Now, to my understanding the initial idea was that this should not be a problem in a Muslim community since the religion discourages behaviour that leaves anyone at a loss, however non-Muslim customers are also allowed access to Islamic financial products. In that case, there would be no reason why a non-Muslim customer should benefit from the fiscal loss of the Islamic bank – after all they are not tied down by their religion. Consequently, non-Muslim customers produce a shifting effect that depletes the earnings of Islamic banks. In this way, there isn’t much money to be made from Islamic banking. Equally, the problem with this is that it rejects Islamic banking on the basis that non-Muslim customers turning to IB products will have detrimental effects on the total system, but IB is made to facilitate the needs of non-Muslim customers too.',
        m: '6. The foundation for IB products varies depending on the interpretation of fatwa. Any Islamic financial and economic concepts which are not yet clearly understood from the Quran and Sunnah (the archives of Muhammad’s words) are then clarified through fatwa. The problem here for the IB systems is that no monolithic authority governs the industry. This stems from the different interpretations of Sharia rulings which can be traced to the different sects in Islam, of which all have their own authority or body to provide guidance and interpretation on Sharia issues. Consequently, what may be interpreted in one way by this sect may be interpreted in a completely different way by another.',
        n: '7. There is sometimes a lack of confidence in the IB system. The diversity of views among Islamic scholars when considering the ruling of products within the industry means that customers or investors often lack confidence in whether a product is in fact Sharia-compliant. This is a major problem for IB systems because if a customer or investor does not believe that the product is what the bank claims it to be then it cannot be sold.',
        o: 'To tackle this problem of standardisation, there are regulatory bodies such as the Islamic Financial Services Board (IFSB) and the Accounting and Auditing Organisation for Islamic Financial Institutions (AAOIFI), but this often results in religious experts standing in opposition to organisations due to a lack of consensus.',
        p: 'Subsequently, what we then find is that, as asserted by M. S. Malik, these Sharia boards are unpredictable and convoluted because the scholars on the boards are not well-equipped in both finance and religion. Applying this directly to the Islamic banking system then results in a lack of employees that are skilled in financial operations or knowledgeable about Sharia law. The consequence of this is that these banking systems either produce products that are not Sharia-compliant depending on the interpretation taken, or that they are Sharia-compliant but the bank takes a loss.',
        q: 'Conclusion',
        r: 'The problems found in Islamic banking are closely tied to inconsistencies resulting from two colliding worlds – the financial and the religious. These problems vary depending on the bank since each one is independently assessed by regulatory bodies. Above, we have looked at two sides of the same coin. Islamic banking systems can be useful, whether it be to take out an interest-free mortgage loan for one’s start-up business or any other form of delayed payment. However, they are also prone to losing lots of money due to some of the reasons I have already mentioned. A key question worth pondering is: does the customer of an Islamic bank wish to purchase a product that results in a loss for the bank (a bank which has as its core principle the fair treatment of that same customer)?',
        s: 'Some reading this may question why any of this matters to you. In this world, a failure to plan is a plan to fail – a maxim that speaks no louder than in the aftermath of the 2008 economic crisis. In researching Islamic banking I have found that by removing interest-based banking products, one is better able to plan a financial move. This stands out most vividly to any hopeful entrepreneurs committed to making money moves. In most cases, I would rather not pay high-interest rates on a financial loan that was needed to solidify the foundations of my start-up business. From a consumer’s point of view, I would rather not pay high-interest rates on a loan that was needed to finance a fundamental feature of my consumerist lifestyle i.e. a smartphone or a laptop. In short, I would rather not pay high-interest rates full stop.',
        t: 'By attempting to understand Islamic banking, you are empowering yourself with knowledge that could help you make more advantageous money moves. Put more succinctly, knowledge is power and Islamic knowledge, well, that’s still power.'
    }
}

export default content